DROP TABLE IF EXISTS `#__huge_it_videogallery_videos`;

CREATE TABLE IF NOT EXISTS `#__huge_it_videogallery_videos` (
   `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `videogallery_id` varchar(200) DEFAULT NULL,
  `description` text,
  `image_url` text,
  `sl_url` varchar(128) DEFAULT NULL,
  `sl_type` text NOT NULL,
  `link_target` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` tinyint(4) unsigned DEFAULT NULL,
  `published_in_sl_width` tinyint(4) unsigned DEFAULT NULL,
  `thumb_url` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=10 ;


INSERT INTO `#__huge_it_videogallery_videos` (`id`, `name`, `videogallery_id`, `description`, `image_url`, `sl_url`, `sl_type`, `link_target`, `ordering`, `published`, `published_in_sl_width`, `thumb_url`) VALUES
(1, 'People Are Awesome', '1', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'https://www.youtube.com/embed/yNHyTk2jYNA', '', 'video', 'on', 0, 1, NULL, ''),
(2, 'Africa Race', '1', '<ul><li>lorem ipsumdolor sit amet</li><li>lorem ipsum dolor sit amet</li></ul><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'http://player.vimeo.com/video/62604342', 'http://huge-it.com/fields/order-website-maintenance/', 'video', 'on', 1, 1, NULL, ''),
(3, 'London City In Motion', '1', '<h6>Lorem Ipsum </h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><ul><li>lorem ipsum</li><li>dolor sit amet</li><li>lorem ipsum</li><li>dolor sit amet</li></ul>', 'http://player.vimeo.com/video/99310168', 'http://huge-it.com/fields/order-website-maintenance/', 'video', 'on', 2, 1, NULL, ''),
(4, 'Dubai City As You have Never Seen It Before', '1', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p><h6>Dolor sit amet</h6><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'https://www.youtube.com/embed/t5vta25jHQI', 'http://huge-it.com/fields/order-website-maintenance/', 'video', 'on', 3, 1, NULL, ''),
(5, 'Never say no to a Panda !', '1', '<h6>Lorem Ipsum</h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'http://player.vimeo.com/video/15371143', 'http://huge-it.com/', 'video', 'on', 4, 1, NULL, ''),
(6, 'INDO-FLU', '1', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p>', 'http://player.vimeo.com/video/103151169', 'http://huge-it.com/fields/order-website-maintenance/', 'video', 'on', 5, 1, NULL, ''),
(7, 'People Are Awesome Womens Edition', '1', '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p><h6>Lorem Ipsum</h6><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>', 'https://www.youtube.com/embed/R5avCAn1vs0', 'http://huge-it.com/fields/order-website-maintenance/', 'video', 'on', 6, 1, NULL, ''),
(8, 'Norwey', '1', '<h6>Lorem Ipsum </h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><ul><li>lorem ipsum</li><li>dolor sit amet</li><li>lorem ipsum</li><li>dolor sit amet</li></ul>', 'http://player.vimeo.com/video/31022539', 'http://huge-it.com/fields/order-website-maintenance/', 'video', 'on', 7, 1, NULL, ''),
(9, 'Slow Motion', '1', '<h6>Lorem Ipsum </h6><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. </p><p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><ul><li>lorem ipsum</li><li>dolor sit amet</li><li>lorem ipsum</li><li>dolor sit amet</li></ul>', 'https://www.youtube.com/embed/gb69WX82Hvs', 'http://huge-it.com/', 'video', 'on', 8, 1, NULL, '');


DROP TABLE IF EXISTS `#__huge_it_videogallery_params`;


CREATE TABLE IF NOT EXISTS `#__huge_it_videogallery_params` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `title` varchar(200) CHARACTER SET utf8 NOT NULL,
  `description` text CHARACTER SET utf8 NOT NULL,
  `value` varchar(200) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=183 ;

INSERT INTO `#__huge_it_videogallery_params` (`id`,`name`, `title`, `description`, `value`) VALUES
(8, 'ht_view2_element_linkbutton_text', 'Link Button Text', 'Link Button Text', 'View More'),
(9, 'ht_view2_element_show_linkbutton', 'Show Link Button On Element', 'Show Link Button On Element', 'on'),
(10, 'ht_view2_element_linkbutton_color', 'Element Link Button Font Color', 'Element Link Button Font Color', 'FFFFFF'),
(11, 'ht_view2_element_linkbutton_font_size', 'Element Link Button Font Size', 'Element Link Button Font Size', '14'),
(12, 'ht_view2_element_linkbutton_background_color', 'Element Link Button Background Color', 'Element Link Button Background Color', 'FF2C2C'),
(13, 'ht_view2_show_popup_linkbutton', 'Show Link Button On Popup', 'Show Link Button On Popup', 'on'),
(14, 'ht_view2_popup_linkbutton_text', 'Popup Link Button Text', 'Link Button Text', 'View More'),
(15, 'ht_view2_popup_linkbutton_background_hover_color', 'Link Button Background Hover Color', 'Link Button Background Hover Color', 'C02121'),
(16, 'ht_view2_popup_linkbutton_background_color', 'Link Button Background Color', 'Link Button Background Color', 'FF2C2C'),
(17, 'ht_view2_popup_linkbutton_font_hover_color', 'Link Button Font Hover Color', 'Link Button Font Hover Color', 'FFFFFF'),
(18, 'ht_view2_popup_linkbutton_color', 'Element Link Button Font Color', 'Link Button Font Color', 'FFFFFF'),
(19, 'ht_view2_popup_linkbutton_font_size', 'Element Link Button Font Size', 'Link Button Font Size', '14'),
(20, 'ht_view2_description_color', 'Description Font Color', 'Description Font Color', '222222'),
(21, 'ht_view2_description_font_size', 'Description Font Size', 'Description Font Size', '14'),
(22, 'ht_view2_show_description', 'Show Description', 'Show Description', 'on'),
(23, 'ht_view2_thumbs_width', 'Thumbnails Width', 'Thumbnails Width', '75'),
(24, 'ht_view2_thumbs_height', 'Thumbnails Height', 'Thumbnails Height', '75'),
(25, 'ht_view2_thumbs_position', 'Thumbnails Position', 'Thumbnails Position', 'before'),
(26, 'ht_view2_show_thumbs', 'Show Thumbnails', 'Show Thumbnails', 'on'),
(27, 'ht_view2_popup_background_color', 'Popup Background Color', 'Popup Background Color', 'FFFFFF'),
(28, 'ht_view2_popup_overlay_color', 'Popup Overlay Color', 'Popup Overlay Color', '000000'),
(29, 'ht_view2_popup_overlay_transparency_color', 'Popup Overlay Transparency', 'Popup Overlay Transparency ', '70'),
(30, 'ht_view2_popup_closebutton_style', 'Popup Close Button Style', 'Popup Close Button Style', 'dark'),
(31, 'ht_view2_show_separator_lines', 'Show Separator Lines', 'Show Separator Lines', 'on'),
(32, 'ht_view2_show_popup_title', 'Show Popup Title', 'Show Popup Title', 'on'),
(33, 'ht_view2_element_title_font_size', 'Element Title Font Size', 'Element Title Font Size', '18'),
(34, 'ht_view2_element_title_font_color', 'Element Title Font Color', 'Element Title Font Color', '222222'),
(35, 'ht_view2_popup_title_font_size', 'Popup Title Font Size', 'Popup Title Font Size', '18'),
(36, 'ht_view2_popup_title_font_color', 'Popup Title Font Color', 'Popup Title Font Color', '222222'),
(37, 'ht_view2_element_overlay_color', 'Element Overlay Color', 'Element Overlay Color', 'FFFFFF'),
(38, 'ht_view2_element_overlay_transparency', 'Element Overlay Transparency', 'Element Overlay Transparency ', '70'),
(39, 'ht_view2_zoombutton_style', 'Zoom Button Style', 'Zoom Button Style', 'light'),
(40, 'ht_view2_element_border_width', 'Element Border Width', 'Element Border Width', '1'),
(41, 'ht_view2_element_border_color', 'Element Border Color', 'Element Border Color', 'DEDEDE'),
(42, 'ht_view2_element_background_color', 'Element Background Color', 'Element Background Color', 'F9F9F9'),
(43, 'ht_view2_element_width', 'Block Width', 'Block Width', '275'),
(44, 'ht_view2_element_height', 'Block Height', 'Block Height', '160'),
(45, 'ht_view5_icons_style', 'Icons Style', 'Icons Style', 'dark'),
(46, 'ht_view5_show_separator_lines', 'Show Separator Lines', 'Show Separator Lines', 'on'),
(47, 'ht_view5_linkbutton_text', 'Link Button Text', 'Link Button Text', 'View More'),
(48, 'ht_view5_show_linkbutton', 'Show Link Button', 'Show Link Button', 'on'),
(49, 'ht_view5_linkbutton_background_hover_color', 'Link Button Background Hover Color', 'Link Button Background Hover Color', 'C02121'),
(50, 'ht_view5_linkbutton_background_color', 'Link Button Background Color', 'Link Button Background Color', 'FF2C2C'),
(51, 'ht_view5_linkbutton_font_hover_color', 'Link Button Font Hover Color', 'Link Button Font Hover Color', 'FFFFFF'),
(52, 'ht_view5_linkbutton_color', 'Link Button Font Color', 'Link Button Font Color', 'FFFFFF'),
(53, 'ht_view5_linkbutton_font_size', 'Link Button Font Size', 'Link Button Font Size', '14'),
(54, 'ht_view5_description_color', 'Description Font Color', 'Description Font Color', '555555'),
(55, 'ht_view5_description_font_size', 'Description Font Size', 'Description Font Size', '14'),
(56, 'ht_view5_show_description', 'Show Description', 'Show Description', 'on'),
(57, 'ht_view5_thumbs_width', 'Thumbnails Width', 'Thumbnails Width', '75'),
(58, 'ht_view5_thumbs_height', 'Thumbnails Height', 'Thumbnails Hight', '75'),
(59, 'ht_view5_show_thumbs', 'Show Thumbnails', 'Show Thumbnails', 'on'),
(60, 'ht_view5_title_font_size', 'Title Font Size', 'Title Font Size', '16'),
(61, 'ht_view5_title_font_color', 'Title Font Color', 'Title Font Color', 'C02121'),
(62, 'ht_view5_main_image_width', 'Main Image Width', 'Main Image Width', '275'),
(63, 'ht_view5_slider_tabs_font_color', 'Slider Tabs Font Color', 'Slider Tabs Font Color', 'd9d99'),
(64, 'ht_view5_slider_tabs_background_color', 'Slider Tabs Background Color', 'Slider Tabs Background Color', '555555'),
(65, 'ht_view5_slider_background_color', 'Slider Background Color', 'Slider Background Color', 'F9F9F9'),
(66, 'ht_view6_title_font_size', 'Title Font Size', 'Title Font Size', '16'),
(67, 'ht_view6_title_font_color', 'Title Font Color', 'Title Font Color', 'C02121'),
(68, 'ht_view6_title_font_hover_color', 'Title Font Hover Color', 'Title Font Hover Color', 'FF2C2C'),
(69, 'ht_view6_title_background_color', 'Title Background Color', 'Title Background Color', '000000'),
(70, 'ht_view6_title_background_transparency', 'Title Background Transparency', 'Title Background Transparency', '80'),
(71, 'ht_view6_border_radius', 'Image Border Radius', 'Image Border Radius', '3'),
(72, 'ht_view6_border_width', 'Image Border Width', 'Image Border Width', '0'),
(73, 'ht_view6_border_color', 'Image Border Color', 'Image Border Color', 'EEEEEE'),
(74, 'ht_view6_width', 'Image Width', 'Image Width', '275'),
(75, 'light_box_size', 'Light box size', 'Light box size', '17'),
(76, 'light_box_width', 'Light Box width', 'Light Box width', '800'),
(77, 'light_box_transition', 'Light Box Transition', 'Light Box Transition', 'elastic'),
(78, 'light_box_speed', 'Light box speed', 'Light box speed', '800'),
(79, 'light_box_href', 'Light box href', 'Light box href', 'False'),
(80, 'light_box_title', 'Light box Title', 'Light box Title', 'false'),
(81, 'light_box_scalephotos', 'Light box scalePhotos', 'Light box scalePhotos', 'true'),
(82, 'light_box_rel', 'Light Box rel', 'Light Box rel', 'false'),
(83, 'light_box_scrolling', 'Light box Scrollin', 'Light box Scrollin', 'false'),
(84, 'light_box_opacity', 'Light box Opacity', 'Light box Opacity', '20'),
(85, 'light_box_open', 'Light box Open', 'Light box Open', 'false'),
(86, 'light_box_overlayclose', 'Light box overlayClose', 'Light box overlayClose', 'true'),
(87, 'light_box_esckey', 'Light box escKey', 'Light box escKey', 'false'),
(88, 'light_box_arrowkey', 'Light box arrowKey', 'Light box arrowKey', 'false'),
(89, 'light_box_loop', 'Light box loop', 'Light box loop', 'true'),
(90, 'light_box_data', 'Light box data', 'Light box data', 'false'),
(91, 'light_box_classname', 'Light box className', 'Light box className', 'false'),
(92, 'light_box_fadeout', 'Light box fadeOut', 'Light box fadeOut', '300'),
(93, 'light_box_closebutton', 'Light box closeButton', 'Light box closeButton', 'true'),
(94, 'light_box_current', 'Light box current', 'Light box current', 'image'),
(95, 'light_box_previous', 'Light box previous', 'Light box previous', 'previous'),
(96, 'light_box_next', 'Light box next', 'Light box next', 'next'),
(97, 'light_box_close', 'Light box close', 'Light box close', 'close'),
(98, 'light_box_iframe', 'Light box iframe', 'Light box iframe', 'false'),
(99, 'light_box_inline', 'Light box inline', 'Light box inline', 'false'),
(100, 'light_box_html', 'Light box html', 'Light box html', 'false'),
(101, 'light_box_photo', 'Light box photo', 'Light box photo', 'false'),
(102, 'light_box_height', 'Light box height', 'Light box height', '600'),
(103, 'light_box_innerwidth', 'Light box innerWidth', 'Light box innerWidth', 'false'),
(104, 'light_box_innerheight', 'Light box innerHeight', 'Light box innerHeight', 'false'),
(105, 'light_box_initialwidth', 'Light box initialWidth', 'Light box initialWidth', '300'),
(106, 'light_box_initialheight', 'Light box initialHeight', 'Light box initialHeight', '100'),
(107, 'light_box_maxwidth', 'Light box maxWidth', 'Light box maxWidth', ''),
(108, 'light_box_maxheight', 'Light box maxHeight', 'Light box maxHeight', ''),
(109, 'light_box_slideshow', 'Light box slideshow', 'Light box slideshow', 'false'),
(110, 'light_box_slideshowspeed', 'Light box slideshowSpeed', 'Light box slideshowSpeed', '2500'),
(111, 'light_box_slideshowauto', 'Light box slideshowAuto', 'Light box slideshowAuto', 'true'),
(112, 'light_box_slideshowstart', 'Light box slideshowStart', 'Light box slideshowStart', 'start slideshow'),
(113, 'light_box_slideshowstop', 'Light box slideshowStop', 'Light box slideshowStop', 'stop slideshow'),
(114, 'light_box_fixed', 'Light box fixed', 'Light box fixed', 'true'),
(115, 'light_box_top', 'Light box top', 'Light box top', 'false'),
(116, 'light_box_bottom', 'Light box bottom', 'Light box bottom', 'false'),
(117, 'light_box_left', 'Light box left', 'Light box left', 'false'),
(118, 'light_box_right', 'Light box right', 'Light box right', 'false'),
(119, 'light_box_reposition', 'Light box reposition', 'Light box reposition', 'false'),
(120, 'light_box_retinaimage', 'Light box retinaImage', 'Light box retinaImage', 'true'),
(121, 'light_box_retinaurl', 'Light box retinaUrl', 'Light box retinaUrl', 'false'),
(122, 'light_box_retinasuffix', 'Light box retinaSuffix', 'Light box retinaSuffix', '@2x.$1'),
(123, 'light_box_returnfocus', 'Light box returnFocus', 'Light box returnFocus', 'true'),
(124, 'light_box_trapfocus', 'Light box trapFocus', 'Light box trapFocus', 'true'),
(125, 'light_box_fastiframe', 'Light box fastIframe', 'Light box fastIframe', 'true'),
(126, 'light_box_preloading', 'Light box preloading', 'Light box preloading', 'true'),
(127, 'lightbox_open_position', 'Lightbox open position', 'Lightbox open position', '5'),
(128, 'light_box_style', 'Light Box style', 'Light Box style', '1'),
(129, 'light_box_size_fix', 'Light Box size fix style', 'Light Box size fix style', 'false'),
(130, 'slider_crop_image', 'Slider crop image', 'Slider crop image', 'crop'),
(131, 'slider_title_color', 'Slider title color', 'Slider title color', '000000'),
(132, 'slider_title_font_size', 'Slider title font size', 'Slider title font size', '13'),
(133, 'slider_description_color', 'Slider description color', 'Slider description color', 'FFFFFF'),
(134, 'slider_description_font_size', 'Slider description font size', 'Slider description font size', '12'),
(135, 'slider_title_position', 'Slider title position', 'Slider title position', 'right-top'),
(136, 'slider_description_position', 'Slider description position', 'Slider description position', 'right-bottom'),
(137, 'slider_title_border_size', 'Slider Title border size', 'Slider Title border size', '0'),
(138, 'slider_title_border_color', 'Slider title border color', 'Slider title border color', 'FFFFFF'),
(139, 'slider_title_border_radius', 'Slider title border radius', 'Slider title border radius', '4'),
(140, 'slider_description_border_size', 'Slider description border size', 'Slider description border size', '0'),
(141, 'slider_description_border_color', 'Slider description border color', 'Slider description border color', 'FFFFFF'),
(142, 'slider_description_border_radius', 'Slider description border radius', 'Slider description border radius', '0'),
(143, 'slider_slideshow_border_size', 'Slider border size', 'Slider border size', '0'),
(144, 'slider_slideshow_border_color', 'Slider border color', 'Slider border color', 'FFFFFF'),
(145, 'slider_slideshow_border_radius', 'Slider border radius', 'Slider border radius', '0'),
(146, 'slider_navigation_type', 'Slider navigation type', 'Slider navigation type', '1'),
(147, 'slider_navigation_position', 'Slider navigation position', 'Slider navigation position', 'bottom'),
(148, 'slider_title_background_color', 'Slider title background color', 'Slider title background color', 'FFFFFF'),
(149, 'slider_description_background_color', 'Slider description background color', 'Slider description background color', '000000'),
(150, 'slider_title_transparent', 'Slider title has background', 'Slider title has background', 'on'),
(151, 'slider_description_transparent', 'Slider description has background', 'Slider description has background', 'on'),
(152, 'slider_slider_background_color', 'Slider slider background color', 'Slider slider background color', 'FFFFFF'),
(153, 'slider_dots_position', 'slider dots position', 'slider dots position', 'none'),
(154, 'slider_active_dot_color', 'slider active dot color', '', 'FFFFFF'),
(155, 'slider_dots_color', 'slider dots color', '', '000000'),
(156, 'slider_description_width', 'Slider description width', 'Slider description width', '70'),
(157, 'slider_description_height', 'Slider description height', 'Slider description height', '50'),
(158, 'slider_description_background_transparency', 'slider description background transparency', 'slider description background transparency', '70'),
(159, 'slider_description_text_align', 'description text-align', 'description text-align', 'justify'),
(160, 'slider_title_width', 'slider title width', 'slider title width', '30'),
(161, 'slider_title_height', 'slider title height', 'slider title height', '50'),
(162, 'slider_title_background_transparency', 'slider title background transparency', 'slider title background transparency', '70'),
(163, 'slider_title_text_align', 'title text-align', 'title text-align', 'right'),
(164, 'slider_title_has_margin', 'title has margin', 'title has margin', 'off'),
(165, 'slider_description_has_margin', 'description has margin', 'description has margin', 'off'),
(166, 'slider_show_arrows', 'Slider show left right arrows', 'Slider show left right arrows', 'on'),
(167, 'thumb_image_behavior', 'Image Behavior', 'Image Behavior', 'on'),
(168, 'thumb_image_width', 'Image widht', 'Image widht', '240'),
(169, 'thumb_image_height', 'Image height', 'Image height', '150'),
(170, 'thumb_image_border_width', 'Image border width', 'Image border width', '1'),
(171, 'thumb_image_border_color', 'Image border color', 'Image border color', '444444'),
(172, 'thumb_image_border_radius', 'Image border Radius', 'Image border Radius', '5'),
(173, 'thumb_margin_image', 'Margin image', 'Margin image', '1'),
(174, 'thumb_title_font_size', 'Title font size', 'Title font size', '16'),
(175, 'thumb_title_font_color', 'Title font color', 'Title font color', 'FFFFFF'),
(176, 'thumb_title_background_color', 'Title background color', 'Title background color', 'CCCCCC'),
(177, 'thumb_title_background_transparency', 'Title Background Transparency', 'Title Background Transparency', '80'),
(178, 'thumb_box_padding', 'Box padding', 'Box padding', '28'),
(179, 'thumb_box_background', 'Box background', 'Box background', '333333'),
(180, 'thumb_box_use_shadow', 'Box use shadow', 'Box use shadow', 'on'),
(181, 'thumb_box_has_background', 'Box has background', 'Box has background', 'on'),
(182, 'thumb_view_text', 'View Image Text', 'View Image Text', 'Watch Video'),
(183, 'ht_view8_element_cssAnimation', 'Image CssAnimation', 'Image CssAnimation', 'false'),
(184, 'ht_view8_element_height', 'Element Hight', 'Element Hight', '120'),
(185, 'ht_view8_element_maxheight', 'Element MaxHight', 'Element MaxHight', '155'),
(186, 'ht_view8_element_show_caption', 'Show Caption', 'Show Caption', 'true'),
(187, 'ht_view8_element_padding', 'Element Padding', 'Element Padding', '0'),
(188, 'ht_view8_element_border_radius', 'Border Radius', 'Border Radius', '5'),
(189, 'ht_view8_icons_style', 'Icons Style', 'Icons Style', 'dark'),
(190, 'ht_view8_element_title_font_size', 'Element Title Font Size', 'Element Title Font Size', '13'),
(191, 'ht_view8_element_title_font_color', 'Element Title Font Color', 'Element Title Font Color', '3AD6FC'),
(192, 'ht_view8_popup_background_color', 'Popup background Color', 'Popup background Color', '000000'),
(193, 'ht_view8_popup_overlay_transparency_color', 'Popup Overlay Transparency Color', 'Popup Overlay Transparency Color', '0'),
(194, 'ht_view8_popup_closebutton_style', 'Popup Closebutton Style', 'Popup Closebutton Style', 'dark'),
(195, 'ht_view8_element_title_overlay_transparency', 'Element Overlay Transparency', 'Element Overlay Transparency', '90'),
(196, 'ht_view8_element_size_fix', 'Element Size Fix', 'Element Size Fix', 'false'),
(197, 'ht_view8_element_title_background_color', 'Element Title Background Color', 'Element Title Background Color', 'FF1C1C'),
(198, 'ht_view8_element_justify', 'Image Justify', 'Image Justify', 'true'),
(199, 'ht_view8_element_randomize', 'Image Randomize', 'Image Randomize', 'false'),
(200, 'ht_view8_element_animation_speed', 'Image Animation Speed', 'Image Animation Speed', '2000'),
(201, 'video_ht_view9_title_fontsize', 'Title Fontsize', 'Title Fontsize', '18'),
(202, 'video_ht_view9_title_color', 'Title Color', 'Title Color', 'FFFFFF'),
(203, 'video_ht_view9_desc_color', 'Description Color', 'Description Color', '000000'),
(204, 'video_ht_view9_desc_fontsize', 'Description Fontsize', 'Description Fontsize', '14'),
(205, 'video_ht_view9_element_title_show', 'Show/Hide Title', 'Show/Hide Title', 'true'),
(206, 'video_ht_view9_element_desc_show', 'Show/Hide Description', 'Show/Hide Description', 'true'),
(207, 'video_ht_view9_general_width', 'General Width', 'General Width', '100'),
(208, 'video_view9_general_position', 'General Position', 'General Position', 'center'),
(209, 'video_view9_title_textalign', 'General Textalign', 'General Textalign', 'left'),
(210, 'video_view9_desc_textalign', 'General Description Textalign', 'General Description Textalign', 'justify'),
(211, 'video_view9_image_position', 'Image Position', 'Image Position', '2'),
(212, 'video_ht_view9_title_back_color', 'Background Color', 'Background Color', '000000'),
(213, 'video_ht_view9_title_opacity', 'Title Opacity', 'Title Opacity', '70'),
(214, 'video_ht_view9_desc_opacity', 'Description Opacity', 'Description Opacity', '100'),
(215, 'video_ht_view9_desc_back_color', 'Background Color', 'Background Color', 'FFFFFF'),
(216, 'video_ht_view9_general_space', 'Space', 'Space', '0'),
(217, 'video_ht_view9_general_separator_size', 'Separator Size', 'Separator Size', '0'),
(218, 'video_ht_view9_general_separator_color', 'Separator Color', 'Separator Color', '010457'),
(219, 'video_view9_general_separator_style', 'Separator Style', 'Separator Style', 'dotted'),
(220, 'video_ht_view9_paginator_fontsize', 'Paginator Fontsize', 'Paginator Fontsize', '22'),
(221, 'video_ht_view9_paginator_color', 'Paginator Color', 'Paginator Color', '1046B3'),
(222, 'video_ht_view9_paginator_icon_color', 'Paginator Icons Color', 'Paginator Icons Color', '1046B3'),
(223, 'video_ht_view9_paginator_icon_size', 'Paginator Icons Size', 'Paginator Icons Size', '18'),
(224, 'video_view9_paginator_position', 'Paginator Position', 'Paginator Position', 'center'),
(225, 'video_ht_view9_video_width', 'Video Width', 'Video Width', '720'),
(226, 'video_ht_view9_video_height', 'Video Height', 'Video Height', '430'),
(227, 'video_view9_video_position', 'Video Position', 'Video Position', 'center'),
(228, 'video_view9_loadmore_position', 'Load More Position', 'Load More Position', 'center'),
(229, 'video_ht_view9_loadmore_fontsize', 'Load More Font Size', 'Load More Font Size', '19'),
(230, 'video_ht_view9_button_color', 'Load More Button Color', 'Load More Button Color', '5CADFF'),
(231, 'video_ht_view9_loadmore_font_color', 'Load More Font Color', 'Load More Font Color', 'FFFFFF'),
(232, 'video_ht_view9_loadmore_font_color', 'Load More Text', 'Load More Text', 'FFFFFF'),
(233, 'loading_type', 'Loading GIF', 'Loading GIF', '2'),
(234, 'video_ht_view9_loadmore_text', 'Load More Text', 'Load More Text', 'View More'),
(235, 'video_ht_view8_paginator_position', 'Paginator Position', 'Paginator Position', 'center'),
(236, 'video_ht_view8_paginator_icon_size', 'Paginator Icons Size', 'Paginator Icons Size', '18'),
(237, 'video_ht_view8_paginator_icon_color', 'Paginator Icons Color', 'Paginator Icons Color', '26A6FC'),
(238, 'video_ht_view8_paginator_color', 'Paginator Color', 'Paginator Color', '26A6FC'),
(239, 'video_ht_view8_paginator_fontsize', 'Paginator Fontsize', 'Paginator Fontsize', '18'),
(240, 'video_ht_view8_loadmore_position', 'Load More Position', 'Load More Position', 'center'),
(241, 'video_ht_view8_loadmore_fontsize', 'Load More Font Size', 'Load More Font Size', '14'),
(242, 'video_ht_view8_button_color', 'Load More Button Color', 'Load More Button Color', '26A6FC'),
(243, 'video_ht_view8_loadmore_font_color', 'Load More Font Color', 'Load More Font Color', 'FF1C1C'),
(244, 'video_ht_view8_loading_type', 'Loading GIF', 'Loading GIF', '3'),
(245, 'video_ht_view8_loadmore_text', 'Load More Text', 'Load More Text', 'View More'),
(246, 'video_ht_view7_paginator_fontsize', 'Paginator Fontsize', 'Paginator Fontsize', '22'),
(247, 'video_ht_view7_paginator_color', 'Paginator Color', 'Paginator Color', '0A0202'),
(248, 'video_ht_view7_paginator_icon_color', 'Paginator Icons Color', 'Paginator Icons Color', '333333'),
(249, 'video_ht_view7_paginator_icon_size', 'Paginator Icons Size', 'Paginator Icons Size', '22'),
(250, 'video_ht_view7_paginator_position', 'Paginator Position', 'Paginator Position', 'center'),
(251, 'video_ht_view7_loadmore_position', 'Load More Position', 'Load More Position', 'center'),
(252, 'video_ht_view7_loadmore_fontsize', 'Load More Font Size', 'Load More Font Size', '19'),
(253, 'video_ht_view7_button_color', 'Load More Button Color', 'Load More Button Color', '333333'),
(254, 'video_ht_view7_loadmore_font_color', 'Load More Font Color', 'Load More Font Color', 'CCCCCC'),
(255, 'video_ht_view7_loading_type', 'Loading GIF', 'Loading GIF', '1'),
(256, 'video_ht_view7_loadmore_text', 'Load More Text', 'Load More Text', 'View More'),
(257, 'video_ht_view4_paginator_fontsize', 'Paginator Fontsize', 'Paginator Fontsize', '19'),
(258, 'video_ht_view4_paginator_color', 'Paginator Color', 'Paginator Color', 'FF2C2C'),
(259, 'video_ht_view4_paginator_icon_color', 'Paginator Icons Color', 'Paginator Icons Color', 'B82020'),
(260, 'video_ht_view4_paginator_icon_size', 'Paginator Icons Size', 'Paginator Icons Size', '21'),
(261, 'video_ht_view4_paginator_position', 'Paginator Position', 'Paginator Position', 'center'),
(262, 'video_ht_view4_loadmore_position', 'Load More Position', 'Load More Position', 'center'),
(263, 'video_ht_view4_loadmore_fontsize', 'Load More Font Size', 'Load More Font Size', '16'),
(264, 'video_ht_view4_button_color', 'Load More Button Color', 'Load More Button Color', '5CADFF'),
(265, 'video_ht_view4_loadmore_font_color', 'Load More Font Color', 'Load More Font Color', 'FF0D0D'),
(266, 'video_ht_view4_loading_type', 'Loading GIF', 'Loading GIF', '4'),
(267, 'video_ht_view4_loadmore_text', 'Load More Text', 'Load More Text', 'View More'),
(268, 'video_ht_view1_paginator_fontsize', 'Paginator Fontsize', 'Paginator Fontsize', '22'),
(269, 'video_ht_view1_paginator_color', 'Paginator Color', 'Paginator Color', '222222'),
(270, 'video_ht_view1_paginator_icon_color', 'Paginator Icons Color', 'Paginator Icons Color', 'FF2C2C'),
(271, 'video_ht_view1_paginator_icon_size', 'Paginator Icons Size', 'Paginator Icons Size', '22'),
(272, 'video_ht_view1_paginator_position', 'Paginator Position', 'Paginator Position', 'left'),
(273, 'video_ht_view1_loadmore_position', 'Load More Position', 'Load More Position', 'center'),
(274, 'video_ht_view1_loadmore_fontsize', 'Load More Font Size', 'Load More Font Size', '22'),
(275, 'video_ht_view1_button_color', 'Load More Button Color', 'Load More Button Color', 'FF2C2C'),
(276, 'video_ht_view1_loadmore_font_color', 'Load More Font Color', 'Load More Font Color', 'FFFFFF'),
(277, 'video_ht_view1_loading_type', 'Loading GIF', 'Loading GIF', '2'),
(278, 'video_ht_view1_loadmore_text', 'Load More Text', 'Load More Text', 'Load More'),
(279, 'video_ht_view9_loadmore_font_color_hover', 'Load More Font Hover', 'Load More Font Hover', 'D9D9D9'),
(280, 'video_ht_view9_button_color_hover', 'Load More Background Hover', 'Load More Background Hover', '8F827C'),
(281, 'video_ht_view8_loadmore_font_color_hover', 'Load More Font Hover', 'Load More Font Hover', 'FF4242'),
(282, 'video_ht_view8_button_color_hover', 'Load More Background Hover', 'Load More Background Hover', '0FEFFF'),
(283, 'video_ht_view7_loadmore_font_color_hover', 'Load More Font Hover', 'Load More Font Hover', 'D9D9D9'),
(284, 'video_ht_view7_button_color_hover', 'Load More Background Hover', 'Load More Background Hover', '8F827C'),
(285, 'video_ht_view4_loadmore_font_color_hover', 'Load More Font Hover', 'Load More Font Hover', 'FF4040'),
(286, 'video_ht_view4_button_color_hover', 'Load More Background Hover', 'Load More Background Hover', '99C5FF'),
(287, 'video_ht_view1_loadmore_font_color_hover', 'Load More Font Hover', 'Load More Font Hover', 'F2F2F2'),
(288, 'video_ht_view1_button_color_hover', 'Load More Background Hover', 'Load More Background Hover', '991A1A'),
(289, 'ht_view2_content_in_center_popup', 'Center Content Popup', 'Center Content Popup', 'on'),
(290, 'ht_view2_content_in_center_lightbox', 'Center Content Lightbox', 'Center Content Lightbox', 'off'),
(291, 'video_natural_size_thumbnail', 'Image Resize-Natural', 'Image Resize-Natural', 'resize'),
(292, 'video_natural_size_contentpopup', 'Image Resize-Natural', 'Image Resize-Natural', 'resize');



DROP TABLE IF EXISTS `#__huge_it_videogallery_galleries`;

CREATE TABLE IF NOT EXISTS `#__huge_it_videogallery_galleries` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `sl_height` int(11) unsigned DEFAULT NULL,
  `sl_width` int(11) unsigned DEFAULT NULL,
  `pause_on_hover` text,
  `videogallery_list_effects_s` text,
  `description` text,
  `param` text,
  `sl_position` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` text,
  `huge_it_sl_effects` text NOT NULL,
  `display_type` int(11) DEFAULT '2',
  `content_per_page` int(11) DEFAULT '5',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;


INSERT INTO `#__huge_it_videogallery_galleries` (`id`, `name`, `sl_height`, `sl_width`, `pause_on_hover`, `videogallery_list_effects_s`, `description`, `param`, `sl_position`, `ordering`, `published`, `huge_it_sl_effects`, `display_type`, `content_per_page`) VALUES
(1, 'My First Video Gallery', 375, 1111, 'on', 'none', '4000', '1000', 'center', 1, '300', '7', 1, 2);
